## Monitoring Parameters ##
track:
  logger: CRITICAL
  bar: true

## Game Parameters ##
game:
  gain: 2
  penalty: -3
  sanction: -10
  prefs: -1

## Grid Environment Parameters ##
grid:
  rows: 2
  cols: 3
  merge: 0.4
  minR: 2
  wR: 0.2

  viz:
    freq: 1000
    cell_size: 100
    border_width: 2
    screen_color: Black
    live: false

## Human Player Parameters ##
human:
  type: human

  style: 
    name: 1

    difficulty:
      "0": 0.05
      "1": 0.1
      "2-3": 0.2
      "4-5": 0.25
      "6+": 0.4

    taste:
      warm: 0.05
      cool: 0.95

    minimalism: 0.08

  model: HDQN

  criterion:
    name: SmoothL1Loss
    params:
      beta: 1.0

  optimizer:
    name: AdamW
    params: 
      lr: 0.001
      weight_decay: 0.00001

  tau: 0.005
  batch_size: 8
  gamma: 0
  memory: 100000

## Q-Learning Parameters ##
qlearn:
  repeats: 10000
  epsilon: 1
  cutoff: 0.5
  patience: 10
  visualize: true
  phase: learning

## Simulation Parameters ##
simulate:
  human: 1
  robot: 2
  repeats: 500
