track:
  logger: INFO
  bar: false

game:
  gain: 1
  penalty: -2
  sanction: -10
  delay: -0.5
  title: CA_x_L
grid:
  rows: 4
  cols: 5
  merge: 0.4
  minR: 2
  wR: 0.2

  viz:
    freq: 280
    last_k: 10
    cell_size: 100
    border_width: 2
    screen_color: Black
    live: false

human:
  type: human

  style:
    name: CA
    weights:
    - 0
    - 0
    - 0

    difficulty:
      '0': -1.0
      '1': -0.71
      '2': -0.43
      '3': -0.14
      '4': 0.14
      '5': 0.43
      '6': 0.71
      7+: 1.0

    taste:
      warm: -1
      cool: 1

    minimalism:
      '0': 0
      '1': 0
      '2': 0
      '3': 0
      4+: 0

  model: ConvDQN

  criterion:
    name: SmoothL1Loss
    params:
      beta: 1.0

  optimizer:
    name: AdamW
    params:
      lr: 0.0005
      weight_decay: 0.00001

  tau: 0.005
  batch_size: 64
  gamma: 0.7
  memory: 10000000

robot:
  type: robot

  style:
    name: L
    weights:
    - 0
    - 0
    - 0

    difficulty:
      '0': 1.0
      '1': 0.71
      '2': 0.43
      '3': 0.14
      '4': -0.14
      '5': -0.43
      '6': -0.71
      7+: -1.0

    taste:
      warm: 0
      cool: 0

    minimalism:
      '0': 0
      '1': 0
      '2': 0
      '3': 0
      4+: 0

  model: ConvDQN

  criterion:
    name: SmoothL1Loss
    params:
      beta: 1.0

  optimizer:
    name: AdamW
    params:
      lr: 0.0005
      weight_decay: 0.00001

  tau: 0.005
  batch_size: 64
  gamma: 0.7
  memory: 10000000

simulate:
  repeats: 2000
  visualize: true
  top_k: 20
