track:
  logger: INFO
  bar: false

game:
  gain: 2
  penalty: -3
  sanction: -10
  prefs: ~
  title: I_x_I

grid:
  rows: 4
  cols: 5
  merge: 0.4
  minR: 2
  wR: 0.2

  viz:
    freq: 500
    last_k: 5
    cell_size: 100
    border_width: 2
    screen_color: Black
    live: false

human:
  type: human

  style: 
    name: I

    difficulty:
      '0': 0
      '1': 0
      '2': 0
      '3': 0
      '4': 0
      '5': 0
      '6+': 0

    taste:
      warm: 0
      cool: 0

    minimalism: 0

  model: ConvDQN

  criterion:
    name: SmoothL1Loss
    params:
      beta: 1.0

  optimizer:
    name: AdamW
    params: 
      lr: 0.001
      weight_decay: 0.00001

  tau: 0.005
  batch_size: 8
  gamma: 0
  memory: 10000000

robot:
  type: robot

  style: 
    name: I

    difficulty:
      '0': 0
      '1': 0
      '2': 0
      '3': 0
      '4': 0
      '5': 0
      '6+': 0

    taste:
      warm: 0
      cool: 0

    minimalism: 0

  model: ConvDQN

  criterion:
    name: SmoothL1Loss
    params:
      beta: 1.0

  optimizer:
    name: AdamW
    params: 
      lr: 0.001
      weight_decay: 0.00001

  tau: 0.005
  batch_size: 8
  gamma: 0
  memory: 10000000

simulate:
  repeats: 5000
  visualize: true
  top_k: 20