track:
  logger: INFO
  bar: false

game:
  gain: 1
  penalty: -2
  sanction: -10
  prefs: [0, 1, 0]
  title: W

grid:
  rows: 4
  cols: 5
  merge: 0.4
  minR: 2
  wR: 0.2

  viz:
    freq: 500
    last_k: 10
    cell_size: 100
    border_width: 2
    screen_color: Black
    live: false

human:
  type: human

  style: 
    name: W

    difficulty:
      '0':  0
      '1':  0
      '2':  0
      '3':  0
      '4':  0
      '5':  0
      '6':  0
      '7+': 0

    taste:
      warm: 1
      cool: -1

    minimalism: 
      '0':  0
      '1':  0
      '2':  0
      '3':  0
      '4':  0
      '5':  0
      '6':  0
      '7+': 0

  model: ConvDQN

  criterion:
    name: SmoothL1Loss
    params:
      beta: 1.0

  optimizer:
    name: AdamW
    params: 
      lr: 0.0005
      weight_decay: 0.00001

  tau: 0.005
  batch_size: 64
  gamma: 0
  memory: 10000000

qlearn:
  repeats: 2800
  epsilon: 1
  cutoff: 1
  patience: 50
  visualize: true
  top_k: 20